language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hanbs-wp' ]; then cd .. && eval "mv $currentfolder generator-hanbs-wp" && cd generator-hanbs-wp; fi

